In [51]:
from matplotlib import font_manager, rc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from tqdm import tqdm
import warnings
warnings.filterwarnings("always")
warnings.filterwarnings(action='ignore')

sns.set(font_scale=1.4)
# 한글 폰트 사용을 위해서 세팅
font_path = "C:/Windows/Fonts/malgun.TTF"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)

df = pd.read_csv('./data/data_2019_2021_revised.csv')
cols_house = ['소득', '가구주_성별코드', '가구주_연령', '가구주_학력코드', '자동차보유대수', '주택소유유무', '가구구분코드','가구원수','취업인원수','세대구분코드']
df = df[cols_house]

# 클러스터 라벨
k=9
pred = pd.read_csv('clustering_results/pred_HC_e50_k9_v1.csv')
df['cluster']=pred.values

# 클러스터 관측 수 많은 순으로 정렬 # as_is_list = df.cluster.value_counts().keys()
# 소득 많은 순으로 정렬 # # df.groupby('cluster')['소득'].mean().sort_values(ascending=False).index
as_is_list = df.groupby('cluster')['소득'].mean().sort_values(ascending=False).index
to_be_list = range(1, k+1)
replacing_dict = dict(zip(as_is_list, to_be_list))
df['cluster'] = df['cluster'].replace(replacing_dict)

In [52]:
df

소득  가구주_성별코드  가구주_연령  가구주_학력코드  자동차보유대수  주택소유유무  가구구분코드  가구원수  \
0        425000         2      64         6        0       2       2     1   
1       2682647         1      63         4        1       2       1     3   
2             0         1      58         6        0       2       2     1   
3       3702933         1      29         6        1       2       1     3   
4       2050000         2      58         3        0       2       1     2   
...         ...       ...     ...       ...      ...     ...     ...   ...   
72225   5021610         1      43         5        2       1       1     3   
72226   3717930         1      37         5        1       1       1     3   
72227   5388172         1      51         4        2       1       1     2   
72228   5434060         1      65         8        2       1       2     2   
72229  18635870         1      52         4        1       1       1     2   

       취업인원수  세대구분코드  cluster  
0          0       1        5  
1          2       2        5  
2          0       1        3  
3          1       2        4  
4          1       2        5  
...      ...     ...      ...  
72225      2       2        4  
72226      2       2        4  
72227      1       1        4  
72228      2       1        4  
72229      2       1        1  

[72230 rows x 11 columns]

In [59]:
res, bins = pd.qcut(df['가구주_연령'], 4, labels=False, retbins=True)
bins


array([ 17.,  44.,  56.,  66., 109.])

In [58]:
res, bins = pd.qcut(df['가구주_학력코드'], 4, labels=False, retbins=True)
bins

array([1., 3., 4., 6., 8.])

In [60]:
res, bins = pd.qcut(df['소득'], 4, labels=False, retbins=True)
bins


array([0.0000000e+00, 1.7595695e+06, 3.3500000e+06, 5.5000000e+06,
       1.3952479e+08])

In [47]:
## 그룹 나누기 위해 discrete하게 만들기


df['소득'] = pd.qcut(df['소득'], 4, labels=False).apply(lambda x: x+1)

df['가구주_연령'] = pd.qcut(df['가구주_연령'], 4, labels=False).apply(lambda x: x+1)
df['가구주_학력코드'] = pd.qcut(df['가구주_학력코드'], 4, labels=False).apply(lambda x: x+1)
df['자동차보유대수'] = df['자동차보유대수'].clip(0, 2)
df['가구원수'] = df['가구원수'].clip(0, 3)

df['취업인원수'] = df['취업인원수'].clip(0, 2)

In [48]:
df

소득  가구주_성별코드  가구주_연령  가구주_학력코드  자동차보유대수  주택소유유무  가구구분코드  가구원수  취업인원수  \
0       1         2       3         3        0       2       2     1      0   
1       2         1       3         2        1       2       1     3      2   
2       1         1       3         3        0       2       2     1      0   
3       3         1       1         3        1       2       1     3      1   
4       2         2       3         1        0       2       1     2      1   
...    ..       ...     ...       ...      ...     ...     ...   ...    ...   
72225   3         1       1         3        2       1       1     3      2   
72226   3         1       1         3        1       1       1     3      2   
72227   3         1       2         2        2       1       1     2      1   
72228   3         1       3         4        2       1       2     2      2   
72229   4         1       2         2        1       1       1     2      2   

       세대구분코드  cluster  
0           1        5  
1           2        5  
2           1        3  
3           2        4  
4           2        5  
...       ...      ...  
72225       2        4  
72226       2        4  
72227       1        4  
72228       1        4  
72229       1        1  

[72230 rows x 11 columns]

In [49]:
df.to_csv('로지스틱회귀.csv', index=False)

In [50]:
pd.read_csv('로지스틱회귀.csv')

소득  가구주_성별코드  가구주_연령  가구주_학력코드  자동차보유대수  주택소유유무  가구구분코드  가구원수  취업인원수  \
0       1         2       3         3        0       2       2     1      0   
1       2         1       3         2        1       2       1     3      2   
2       1         1       3         3        0       2       2     1      0   
3       3         1       1         3        1       2       1     3      1   
4       2         2       3         1        0       2       1     2      1   
...    ..       ...     ...       ...      ...     ...     ...   ...    ...   
72225   3         1       1         3        2       1       1     3      2   
72226   3         1       1         3        1       1       1     3      2   
72227   3         1       2         2        2       1       1     2      1   
72228   3         1       3         4        2       1       2     2      2   
72229   4         1       2         2        1       1       1     2      2   

       세대구분코드  cluster  
0           1        5  
1           2        5  
2           1        3  
3           2        4  
4           2        5  
...       ...      ...  
72225       2        4  
72226       2        4  
72227       1        4  
72228       1        4  
72229       1        1  

[72230 rows x 11 columns]